### ISSUE TITLE
Container crashes when Crashplan tries to upload

### ISSUE THREAD

**Issue by yankees9920** [xeor/dockerfiles#4]
This is exactly what I was looking for and I got it up and setup a docker-compose.yml to get it running nicely, however after about 1 minute of runtime the container crashes. When I'm VNC'd into the UI I can see that it says Crashplan is trying to update right before this crash occurs, so I believe it probably has to do with the latest 4.5 update.

Edit: I should have specified that I'm only using the Crashplan Dockerfile which I've pulled from the Docker Hub - https://hub.docker.com/r/xeor/crashplan/~/dockerfile/

Edit 2: Just noticed that the DockerHub version is about 5 months older than the version here. I'll try this and report back.

Edit 3: Just tried using the latest code from this repo and the upgrade notification happened at a different place,  but it still crashed when attempting to upgrade.

**Comment by xeor** [comment]
Hello

This container used to work, but then (after 4.4 I think), they started changing something that made it crash. I got the newest version in there, but after a day or two, it still crashed. So now, it crashes when it tries to upgrade automatic, and some at a random time.

I though about adding the crashplan daemon in a way that made it start up again inside the container if it crashed, but that would be a bad idea if you had a lot of files. It would almost use all its time rescanning and checking which files to backup :/

I actually ended up moving it out of docker as it also ended up using more resources than I wanted on my docker servers.

There should be a way to get this to work as it used to, but I ended up not pursuing it since I wanted to move it anyway. If you get it to work, please tell me what you did to fix the problems :smile:

**Comment by yankees9920** [comment]
Thanks for the quick reply. I ended up going a different route using X11 forwarding instead VNC to connect to the GUI.
http://www.benwagner.net/computing/installing-crashplan-on-headless-server-x11-forwarding/
